TODAY : ""

data:
  raw: "./data/raw/data.csv"
  warehouse: "./data/warehouse"

log:
  summary: "./log/summary.json"

crawler:
  overview:
    limit: -1
    base_url: "https://bonbanh.com"
    additional_url: "/ha-noi/oto-cu-da-qua-su-dung"
    swap_page: "/page,"

preprocesser:
  train: "./data/preprocess/train.parquet"
  test: "./data/preprocess/test.parquet"
  test_size: 0.2
  random_state: 42

models:
  model:
    random_forest: 
      name: "random_forest"
    xgboost: 
      name: "xgboost"
    adaboost: 
      name: "adaboost"
    svm: 
      name: "svm"
  artifact:
    run_id: "./artifacts/run_ids.json"
    candidate: "./artifacts/candidate.json"

registry:
  uri: "http://127.0.0.1:8080"
  experiment_name: "test_pyspark"
  registered_model_name: "Best Model"
