TODAY : ""

data:
  raw: "./data/raw/data.csv"
  warehouse: "./data/warehouse"

log:
  summary: "./log/summary.json"

crawler:
  overview:
    limit: -1
    base_url: "https://bonbanh.com"
    additional_url: "/ha-noi/oto-cu-da-qua-su-dung"
    swap_page: "/page,"


ml_pipeline:
  pipeline_wrapper: "./src/ml_pipeline/pipeline_wrapper.py"
  ml_pipeline_wrapper: "./src/ml_pipeline/ml_pipeline_wrapper.py"
  data:
    train: "./data/model/train"
    test: "./data/model/test"

registry:
  uri: "http://127.0.0.1:5000"
  experiment_name: "test nth"
  registered_model_name: "Best Model"
  registered_ml_pipeline_name: "Best ML Pipeline"
  artifact_name: "ml_pipeline"
  artifact:
    run_id: "./artifacts/run_ids.json"
    candidate: "./artifacts/candidate.json"
